# Generated by Django 2.1.2 on 2018-10-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FloatField(blank=True, default=0.0)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.PersonalAccount')),
            ],
        ),
    ]
